"""
Clean & Complete Uninstaller for PDF Batch Printer Pro.
Completely wipes application files, user configuration (config.json),
shortcuts, registry keys, cache, and temp files from the computer.
"""
import os
import sys
import glob
import shutil
import tempfile
import winreg
import subprocess

if sys.stdout is not None:
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

import customtkinter as ctk

APP_NAME = "PDF Batch Printer Pro"

ctk.set_appearance_mode("Light")
ctk.set_default_color_theme("blue")


def get_install_dir() -> str:
    """Returns the actual installation directory of the program."""
    if getattr(sys, "frozen", False):
        return os.path.dirname(sys.executable)
    return os.path.dirname(os.path.abspath(__file__))


def remove_shortcuts():
    """Removes Desktop and Start Menu shortcuts."""
    try:
        import win32com.client
        shell = win32com.client.Dispatch("WScript.Shell")

        # Desktop
        desktop_dir = shell.SpecialFolders("Desktop")
        for name in [f"{APP_NAME}.lnk", "PDFBatchPrinterPro.lnk"]:
            desktop_lnk = os.path.join(desktop_dir, name)
            if os.path.exists(desktop_lnk):
                try:
                    os.remove(desktop_lnk)
                except Exception:
                    pass

        # Start menu
        programs_dir = shell.SpecialFolders("Programs")
        for folder_name in [APP_NAME, "PDFBatchPrinterPro"]:
            app_menu_dir = os.path.join(programs_dir, folder_name)
            if os.path.exists(app_menu_dir):
                try:
                    shutil.rmtree(app_menu_dir, ignore_errors=True)
                except Exception:
                    pass
    except Exception as exc:
        print(f"Error removing shortcuts: {exc}")


def remove_registry():
    """Removes Windows Registry uninstall and application entries."""
    for root in [winreg.HKEY_CURRENT_USER, winreg.HKEY_LOCAL_MACHINE]:
        for key_path in [
            rf"Software\Microsoft\Windows\CurrentVersion\Uninstall\PDFBatchPrinterPro",
            rf"Software\PDFBatchPrinterPro",
        ]:
            try:
                winreg.DeleteKey(root, key_path)
            except Exception:
                pass


def clean_all_user_data(install_dir: str):
    """Deep cleans all configuration, temporary documents, and cache files."""
    # 1. Clear files in install directory (config.json, logs, sessions)
    if os.path.exists(install_dir):
        for pattern in ["config.json", "*.log", "*.txt", "*.json"]:
            for f in glob.glob(os.path.join(install_dir, pattern)):
                try:
                    os.remove(f)
                except Exception:
                    pass

    # 2. Clear AppData folders if any
    appdata = os.environ.get("APPDATA", "")
    local_appdata = os.environ.get("LOCALAPPDATA", "")
    for base in [appdata, local_appdata]:
        if base:
            target = os.path.join(base, "PDFBatchPrinterPro")
            if os.path.exists(target):
                try:
                    shutil.rmtree(target, ignore_errors=True)
                except Exception:
                    pass

    # 3. Clear temporary files generated by PDF Batch Printer Pro
    temp_dir = tempfile.gettempdir()
    for pattern in [
        "sep_sheet_*.pdf",
        "converted_*.pdf",
        "pdf_batch_*",
        "uninstall_pdf_printer*.bat",
    ]:
        for f in glob.glob(os.path.join(temp_dir, pattern)):
            try:
                if os.path.isdir(f):
                    shutil.rmtree(f, ignore_errors=True)
                else:
                    os.remove(f)
            except Exception:
                pass


class UninstallerApp(ctk.CTk):
    def __init__(self):
        super().__init__()
        self.title(f"Gỡ cài đặt — {APP_NAME}")
        self.geometry("540x350")
        self.minsize(540, 350)
        self.resizable(False, False)

        # Set App Icon if present
        install_dir = get_install_dir()
        ico_file = os.path.join(install_dir, "assets", "app.ico")
        if os.path.exists(ico_file):
            try:
                self.iconbitmap(default=ico_file)
            except Exception:
                pass

        self.delete_data_var = ctk.BooleanVar(value=True)

        self._build_ui()

    def _build_ui(self):
        wrap = ctk.CTkFrame(self, fg_color="#F8FAFC", corner_radius=0)
        wrap.pack(fill="both", expand=True)

        ctk.CTkLabel(
            wrap, text="🗑️", font=ctk.CTkFont(size=40),
        ).pack(pady=(16, 4))

        ctk.CTkLabel(
            wrap, text=f"Gỡ Cài Đặt {APP_NAME}",
            font=ctk.CTkFont(family="Segoe UI", size=18, weight="bold"),
            text_color="#0F172A",
        ).pack(pady=(0, 8))

        self.msg_lbl = ctk.CTkLabel(
            wrap,
            text=f"Bạn có chắc chắn muốn gỡ bỏ hoàn toàn ứng dụng {APP_NAME}\nkhỏi máy tính của bạn không?",
            font=ctk.CTkFont(family="Segoe UI", size=12),
            text_color="#475569", justify="center",
        )
        self.msg_lbl.pack(pady=(0, 12))

        # Checkbox for total wipe
        opt_card = ctk.CTkFrame(wrap, fg_color="#FFFFFF", corner_radius=8, border_width=1, border_color="#CBD5E1")
        opt_card.pack(fill="x", padx=30, pady=(0, 16))

        self.cb_delete_data = ctk.CTkCheckBox(
            opt_card,
            text="Xóa sạch toàn bộ cấu hình (config.json), lịch sử và tệp tin tạm",
            variable=self.delete_data_var,
            font=ctk.CTkFont(family="Segoe UI", size=11, weight="bold"),
            text_color="#1E293B",
            checkbox_width=18, checkbox_height=18,
            corner_radius=4,
        )
        self.cb_delete_data.pack(padx=14, pady=12, anchor="w")

        self.btn_box = ctk.CTkFrame(wrap, fg_color="transparent")
        self.btn_box.pack(pady=(0, 10))

        self.btn_cancel = ctk.CTkButton(
            self.btn_box, text="Hủy bỏ", width=100, height=34,
            command=self._cancel, fg_color="#94A3B8", hover_color="#64748B",
            font=ctk.CTkFont(family="Segoe UI", size=12),
            corner_radius=6,
        )
        self.btn_cancel.pack(side="left", padx=10)

        self.btn_uninstall = ctk.CTkButton(
            self.btn_box, text="Gỡ Cài Đặt", width=120, height=34,
            command=self._do_uninstall, fg_color="#DC2626", hover_color="#B91C1C",
            font=ctk.CTkFont(family="Segoe UI", size=12, weight="bold"),
            corner_radius=6,
        )
        self.btn_uninstall.pack(side="left", padx=10)

    def _do_uninstall(self):
        self.btn_cancel.pack_forget()
        self.cb_delete_data.configure(state="disabled")
        self.btn_uninstall.configure(state="disabled", text="Đang gỡ...")
        self.update_idletasks()

        install_dir = get_install_dir()

        # 1. Remove Shortcuts
        remove_shortcuts()

        # 2. Remove Registry Keys
        remove_registry()

        # 3. Clean user data & temp if requested
        if self.delete_data_var.get():
            clean_all_user_data(install_dir)

        # 4. Self-delete batch script to remove the entire install directory
        temp_dir = tempfile.gettempdir()
        del_bat = os.path.join(temp_dir, "uninstall_pdf_printer_cleanup.bat")
        
        local_app = os.environ.get("LOCALAPPDATA", "")
        roaming_app = os.environ.get("APPDATA", "")

        with open(del_bat, "w", encoding="utf-8") as fp:
            fp.write(f'''@echo off
timeout /t 2 /nobreak >nul
taskkill /F /IM PDFBatchPrinterPro.exe >nul 2>&1
taskkill /F /IM uninstall.exe >nul 2>&1
rd /s /q "{install_dir}" >nul 2>&1
rd /s /q "{local_app}\\PDFBatchPrinterPro" >nul 2>&1
rd /s /q "{roaming_app}\\PDFBatchPrinterPro" >nul 2>&1
del "%~f0" >nul 2>&1
''')

        try:
            subprocess.Popen([del_bat], shell=True, close_fds=True)
        except Exception as exc:
            print(f"Error launching cleanup batch: {exc}")

        self.msg_lbl.configure(
            text=f"✓ Đã gỡ bỏ {APP_NAME} thành công!\nToàn bộ tệp tin và dữ liệu cấu hình đã được xóa sạch.",
            text_color="#16A34A",
        )
        self.btn_uninstall.configure(
            state="normal", text="Đóng",
            fg_color="#16A34A", hover_color="#15803D",
            command=self._close,
        )

    def _cancel(self):
        self.quit()
        self.destroy()

    def _close(self):
        self.quit()
        self.destroy()


def main():
    app = UninstallerApp()
    app.mainloop()


if __name__ == "__main__":
    main()

